version: '3.9'

services:
    web:
        build:
            context: ../..
            dockerfile: docker/dev/Dockerfile
        container_name: web
        restart: always
        volumes:
            - ../..:/app
            - static:/app/static
            - media:/app/media
        ports:
            - "8000:8000"
        command: python app.manage.py runserver

volumes:
    static:
    media: