# Generated by Django 5.2.1 on 2025-05-30 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmember',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubmember',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubmember',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clubmember',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clubmember',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending Approval'), ('test_required', 'Test Required'), ('test_in_progress', 'Test In Progress'), ('test_failed', 'Test Failed'), ('approved', 'Approved - Contract Required'), ('contract_pending', 'Contract Pending'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ClubContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Контракт участника клуба', max_length=200)),
                ('content', models.TextField(help_text='Содержание контракта')),
                ('pdf_template', models.FileField(blank=True, null=True, upload_to='club_contracts/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_template', to='school.club')),
            ],
            options={
                'verbose_name': 'Контракт клуба',
                'verbose_name_plural': 'Контракты клубов',
                'db_table': 'club_contracts',
            },
        ),
        migrations.CreateModel(
            name='ClubMemberContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подписания'), ('signed', 'Подписан'), ('expired', 'Истек'), ('cancelled', 'Отменен')], default='pending', max_length=20)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('digital_signature', models.TextField(blank=True, help_text='Данные ЭЦП', null=True)),
                ('signature_data', models.JSONField(blank=True, help_text='Данные из сертификата ЭЦП', null=True)),
                ('signed_pdf', models.FileField(blank=True, null=True, upload_to='signed_contracts/')),
                ('signature_file', models.FileField(blank=True, null=True, upload_to='signatures/')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.clubcontract')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signed_contracts', to='school.clubmember')),
            ],
            options={
                'verbose_name': 'Подписанный контракт',
                'verbose_name_plural': 'Подписанные контракты',
                'db_table': 'club_member_contracts',
            },
        ),
    ]
