# Generated by Django 5.2.3 on 2025-06-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_clubmember_admin_notes_clubmember_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmembercontract',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='contract_qr_codes/'),
        ),
        migrations.AddField(
            model_name='clubmembercontract',
            name='verification_url',
            field=models.URLField(blank=True, help_text='URL для проверки контракта', null=True),
        ),
    ]
